//
// Created by shecannotsee on 2022/10/24.
//

#ifndef DEVICEENROLLMENTCLOUDSERVICE_SRC_NET_PACKAGEINSTREAMBASE64_H_
#define DEVICEENROLLMENTCLOUDSERVICE_SRC_NET_PACKAGEINSTREAMBASE64_H_

class packageInStreamBase64 {

};

#endif //DEVICEENROLLMENTCLOUDSERVICE_SRC_NET_PACKAGEINSTREAMBASE64_H_
