//
// Created by shecannotsee on 2022/10/20.
//

#ifndef DEVICEENROLLMENTCLOUDSERVICE_SRC_SERVER_IOEVENT_H_
#define DEVICEENROLLMENTCLOUDSERVICE_SRC_SERVER_IOEVENT_H_

class IOEvent {

};

#endif //DEVICEENROLLMENTCLOUDSERVICE_SRC_SERVER_IOEVENT_H_
